name: ca_mce_flutter_sdk_sample
description: Sample App for using Acoustic Campaign SDK

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_acoustic_mobile_push:
    path: ../../plugins/flutter_acoustic_mobile_push
  flutter_acoustic_mobile_push_inbox:
    path: ../../plugins/flutter_acoustic_mobile_push_inbox
  flutter_acoustic_mobile_push_beacon:
    path: ../../plugins/flutter_acoustic_mobile_push_beacon
  flutter_acoustic_mobile_push_geofence:
    path: ../../plugins/flutter_acoustic_mobile_push_geofence
  flutter_acoustic_mobile_push_inapp:
    path: ../../plugins/flutter_acoustic_mobile_push_inapp
  flutter_acoustic_mobile_push_location:
    path: ../../plugins/flutter_acoustic_mobile_push_location
  flutter_ios_notification_service:
    path: ../../plugins/flutter_ios_notification_service
  #flutter_acoustic_mobile_push_snooze:
  #  path: ../../plugins/flutter_acoustic_mobile_push_snooze
  # flutter_acoustic_mobile_push_displayweb:
  #   path: ../../plugins/flutter_acoustic_mobile_push_displayweb
  # flutter_acoustic_mobile_push_calendar:
  #   path: ../../plugins/flutter_acoustic_mobile_push_calendar

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # toggle switch for the different buttons to toggle between
  toggle_switch: ">=1.2.0"
  # event emitters package
  # eventify: ^1.0.0
  # event emitters package
  event: ">=2.0.5"
  # snackbar
  another_flushbar: ">=1.10.25"
  # video player
  video_player: ">=2.2.6"
  #location / geolocator
  # location: ^4.3.0
  # google maps for geofence
  google_maps_flutter: ^2.3.0
  # geofence
  # geofence_service: ">=3.4.4"
  # random id generator
  uuid: ^3.0.5
  # url launcher
  url_launcher: ^6.0.15
  #ibeacon
  #keep below package until next patch
  # flutter_beacon: ^0.5.1
  #intl for dateTime conversion
  intl: ">=0.17.0"
  #html package for rendering inbox json html data
  flutter_html: ">=2.2.0"
  #webview flutter
  webview_flutter_plus: ^0.3.0+2
  #hex color reader for custom sdk bg colors
  hexcolor: ">=2.0.5"
#  location: ^4.3.0

dev_dependencies:
  # test: ^1.20.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
